import { ArrowUpLeft } from "lucide-react";
import { Link } from "wouter";
import { useLocale } from "../contexts/LocaleContext";

export default function Privacy() {
  const { locale } = useLocale();
  const ar = locale === "ar";
  return <main className="legal-page section-pad page-transition"><div className="legal-top"><span className="eyebrow">GLLORIA / {ar ? "الخصوصية" : "PRIVACY"}</span><Link className="text-link" href="/booking">{ar ? "العودة للحجز" : "Back to booking"} <ArrowUpLeft size={16} /></Link></div><h1>{ar ? "بياناتك" : "Your details"}<br /><em>{ar ? "في أمان." : "with care."}</em></h1><div className="legal-copy"><p>{ar ? "نستخدم البيانات التي ترسلينها من نموذج الحجز فقط لمراجعة طلب الاستشارة والتواصل معك بخصوصه عبر WhatsApp أو البريد الإلكتروني الذي تختارينه." : "We use the details you submit through the booking form only to review your consultation request and contact you about it through WhatsApp or the email you choose to provide."}</p><h2>{ar ? "ما الذي نحتفظ به؟" : "What we keep"}</h2><p>{ar ? "قد نحتفظ بالاسم ورقم الهاتف والمدينة وبيانات المشروع والموعد المقترح وملاحظات التواصل اللازمة لمتابعة الطلب. لا تُنشر هذه البيانات على الموقع العام." : "We may retain your name, phone number, city, project details, preferred time, and necessary communication notes to follow up on the request. These details are not published on the public site."}</p><h2>{ar ? "التحكم في بياناتك" : "Your control"}</h2><p>{ar ? "يمكنك طلب تصحيح بياناتك أو حذفها عبر WhatsApp أو البريد الإلكتروني. لا نطلب كلمات مرور أو بيانات دفع من خلال نموذج الحجز." : "You can request correction or deletion of your details through WhatsApp or email. We do not ask for passwords or payment details through the booking form."}</p><p className="legal-updated">{ar ? "آخر تحديث: أغسطس 2026" : "Last updated: August 2026"}</p></div></main>;
}
