#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Split admin-only rules out of client/src/index.css into client/src/admin.css.

WHY
---
index.css is one 5,800-line stylesheet imported from main.tsx, so every public
visitor downloads the admin console's styling — the dashboard shell, the
bookings table, the analytics cards — on the home page. Vite emits it as a
single render-blocking CSS file.

Moving those rules into a stylesheet imported from Admin.tsx lets Vite emit
them as a separate chunk that only loads on /admin.

SAFETY RULE
-----------
A rule moves only when EVERY comma-separated selector in it is admin-only. Any
rule that mixes an admin selector with a public one stays put. Leaving a rule
behind is harmless (a duplicate at worst); moving a public rule by mistake
would break the live site, so the bias is deliberate.

Rules inside @media / @supports blocks are moved into an equivalent wrapper in
the output so their conditions are preserved.
"""
import re
import sys

SRC = "client/src/index.css"
OUT = "client/src/admin.css"

# Derived from the class names actually used in Admin.tsx, AdminAnalytics.tsx
# and AdminBookings.tsx — not guessed from name shape.
ADMIN_PREFIXES = (".admin-", ".analytics-", ".dashboard-")
ADMIN_EXACT_PREFIXES = (
    ".bookings-table",
    ".booking-detail",
    ".booking-filters",
    ".booking-stat",
)
# `.booking-page`, `.booking-panel`, `.booking-progress` etc. belong to the
# PUBLIC booking wizard and must never move.
PUBLIC_BOOKING = (
    ".booking-page",
    ".booking-panel",
    ".booking-progress",
    ".booking-copy",
    ".booking-layout",
    ".booking-step",
    ".booking-review",
    ".booking-success",
    ".booking-back",
    ".booking-notes",
    ".booking-wide",
    ".booking-honeypot",
    ".booking-previous",
    ".booking-whatsapp",
    ".booking-project",
    ".booking-stage",
)


def selector_is_admin(sel: str) -> bool:
    sel = sel.strip()
    if not sel:
        return False
    for public in PUBLIC_BOOKING:
        if public in sel:
            return False
    for pref in ADMIN_PREFIXES + ADMIN_EXACT_PREFIXES:
        if pref in sel:
            return True
    return False


def split_blocks(css: str):
    """Yield (kind, text) for each top-level construct."""
    i, n, start, depth = 0, len(css), 0, 0
    while i < n:
        c = css[i]
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                yield css[start : i + 1]
                start = i + 1
        elif c == ";" and depth == 0:
            yield css[start : i + 1]  # @import / @charset
            start = i + 1
        i += 1
    if start < n:
        yield css[start:]


def rule_selectors(block: str) -> list:
    head = block.split("{", 1)[0]
    return [s.strip() for s in head.split(",") if s.strip()]


def main() -> int:
    css = open(SRC, encoding="utf-8").read()
    kept, moved = [], []

    for block in split_blocks(css):
        stripped = block.strip()
        if not stripped:
            kept.append(block)
            continue

        head = stripped.split("{", 1)[0].strip()

        # Conditional group rules: recurse one level.
        if head.startswith("@media") or head.startswith("@supports"):
            inner = stripped[stripped.index("{") + 1 : stripped.rindex("}")]
            inner_kept, inner_moved = [], []
            for sub in split_blocks(inner):
                if not sub.strip():
                    continue
                sels = rule_selectors(sub)
                if sels and all(selector_is_admin(s) for s in sels):
                    inner_moved.append(sub)
                else:
                    inner_kept.append(sub)
            if inner_moved:
                moved.append(f"{head} {{{''.join(inner_moved)}\n}}")
            if inner_kept:
                kept.append(f"{head} {{{''.join(inner_kept)}\n}}")
            continue

        if head.startswith("@"):  # @import, @theme, @keyframes, @custom-variant
            kept.append(block)
            continue

        sels = rule_selectors(stripped)
        if sels and all(selector_is_admin(s) for s in sels):
            moved.append(block)
        else:
            kept.append(block)

    if not moved:
        print("nothing to move", file=sys.stderr)
        return 1

    header = (
        "/* Glloria admin console styling.\n"
        " *\n"
        " * Split out of index.css and imported from pages/Admin.tsx so Vite emits it\n"
        " * as its own chunk. Public visitors previously downloaded every dashboard,\n"
        " * bookings-table and analytics rule as part of the render-blocking stylesheet\n"
        " * on the home page.\n"
        " *\n"
        " * Generated by scripts/split-admin-css.py — a rule lands here only when every\n"
        " * one of its selectors is admin-only. */\n"
    )
    open(OUT, "w", encoding="utf-8").write(header + "".join(moved).lstrip("\n") + "\n")
    open(SRC, "w", encoding="utf-8").write("".join(kept))

    print(f"moved {len(moved)} rule blocks -> {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
